name: clone workflow
on:
  workflow_dispatch:
jobs:
  jobs_one:
    name: Clone
    runs-on: ubuntu-latest
    steps:
      - name: running
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            cd ../pub
            git clone git@github.com:Enadel710/Enadel710.github.io.git
