name: deployment workflow
on:
  push:
    branches: [main]
jobs:
  jobs_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: running
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd Enadel710.github.io
            git pull
